### ISSUE TITLE
Not able to access CronJobsComponent' of 'ngx-cron-jobs

### ISSUE THREAD

**Issue by prgdubey** [rvalenciano/ngx-cron-jobs-orig#19]
While using ngx-cron-jobs as a viewChild in my component it is showing this warning:
`WARNING in ./src/app/app.component.ts
43:50-67 "export 'CronJobsComponent' was not found in 'ngx-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\cronjobs\node_modules\webpack\lib\dependencies\HarmonyImportSp
ecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\cronjobs\node_modules\webpack\lib\dependencies\HarmonyImportS
pecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\project\cronjobs\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\project\cronjobs\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./src/app/app.component.ts
44:34-51 "export 'CronJobsComponent' was not found in 'ngx-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\cronjobs\node_modules\webpack\lib\dependencies\HarmonyImportSp
ecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\cronjobs\node_modules\webpack\lib\dependencies\HarmonyImportS
pecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\project\cronjobs\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\project\cronjobs\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\project\cronjobs\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`
These are the following dependencies of my project:
`"dependencies": {
    "angular/animations": "^5.0.0",
    "angular/common": "^5.0.0",
    "angular/compiler": "^5.0.0",
    "angular/core": "^5.0.0",
    "angular/forms": "^5.0.0",
    "angular/http": "^5.0.0",
    "angular/platform-browser": "^5.0.0",
    "angular/platform-browser-dynamic": "^5.0.0",
    "angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "ngx-cron-jobs": "^0.4.6",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "angular/cli": "1.6.0",
    "angular/compiler-cli": "^5.0.0",
    "angular/language-service": "^5.0.0",
    "types/jasmine": "~2.5.53",
    "types/jasminewd2": "~2.0.2",
    "types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }`

**Comment by rvalenciano** [comment]
@prgdubey since you're using windows, can you provide a Plunkr here with the issue?

https://plnkr.co/

**Comment by rvalenciano** [comment]
Will close issue, new repo project can be found https://github.com/yp2/ngx-cron-jobs
